FROM docker.io/duplicati/duplicati:2.2.0.1-stable

ENV DUPLICATI__WEBSERVICE_INTERFACE=any
ENV DUPLICATI__WEBSERVICE_PORT=8200
ENV DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES=*

# pragma: allowlist nextline secret
ENV SETTINGS_ENCRYPTION_KEY=change_me 

# pragma: allowlist nextline secret
ENV DUPLICATI__WEBSERVICE_PASSWORD=change_me 

ENV DUPLICATI__SERVER_DATAFOLDER=/data
